//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mplayerc.rc
//
#define IDOK2                           3
#define IDR_MAINFRAME                   128
#define ID_PLAYERSTATUS                 129
#define IDS_RS_TITLEBARTEXTSTYLE        129
#define ID_PLAYERTIME                   130
#define IDS_RS_USEWMASFREADER           130
#define ID_FILE_OPENMEDIA               131
#define ID_FILE_OPENDVD                 132
#define ID_FILE_CLOSEMEDIA              133
#define ID_FILE_LOADSUBTITLE            134
#define ID_FILE_EXIT                    135
#define ID_VIEW_SEEKER                  136
#define ID_VIEW_CONTROLS                137
#define ID_VIEW_INFORMATION             138
#define ID_VIEW_STATISTICS              139
#define ID_VIEW_STATUS                  140
#define ID_VIEW_FULLSCREEN              141
#define ID_VIEW_ZOOM_50                 142
#define ID_VIEW_ZOOM_100                143
#define ID_VIEW_ZOOM_200                144
#define ID_VIEW_KEEPASPECTRATIO         145
#define ID_VIEW_INCSIZE                 146
#define ID_VIEW_DECSIZE                 147
#define ID_VIEW_INCWIDTH                148
#define ID_VIEW_DECWIDTH                149
#define ID_VIEW_INCHEIGHT               150
#define ID_VIEW_DECHEIGHT               151
#define ID_VIEW_RESET                   152
#define ID_VIEW_ALWAYSONTOP             153
#define ID_VIEW_OPTIONS                 154
#define ID_PLAY_PLAY                    155
#define ID_PLAY_PAUSE                   156
#define ID_PLAY_PLAYPAUSE               157
#define ID_PLAY_STOP                    158
#define ID_PLAY_DECRATE                 159
#define ID_PLAY_INCRATE                 160
#define ID_VOLUME_UP                    161
#define ID_VOLUME_DOWN                  162
#define ID_VOLUME_MUTE                  163
#define ID_NAVIGATE_SKIPBACK            164
#define ID_NAVIGATE_SKIPFORWARD         165
#define ID_NAVIGATE_TITLEMENU           166
#define ID_NAVIGATE_ROOTMENU            167
#define ID_NAVIGATE_SUBPICTUREMENU      168
#define ID_NAVIGATE_AUDIOMENU           169
#define ID_NAVIGATE_ANGLEMENU           170
#define ID_NAVIGATE_CHAPTERMENU         171
#define ID_HELP_ABOUT                   173
#define ID_HELP_HOMEPAGE                174
#define IDB_NOAUDIO                     200
#define IDB_MONO                        201
#define IDB_STEREO                      202
#define IDB_ONOFF                       203
#define IDI_SINGLE                      204
#define IDI_MULTI                       205
#define IDR_POPUP                       206
#define IDD_OPENDIALOG                  207
#define IDD_ABOUTBOX                    208
#define IDD_PPAGEPLAYBACK               209
#define IDD_PPAGEPLAYER                 210
#define IDD_PPAGEDVD                    211
#define IDD_PPAGESUBTITLES              212
#define IDD_PPAGEFORMATS                213
#define IDD_PLAYERINFOBAR               214
#define ID_PLAYERTOOLBAR                215
#define ID_FILTERS_PROPERTIES           216
#define IDD_PLAYERSTATUSBAR             217
#define IDD_PLAYERSEEKBAR               218
#define ID_NAVIGATE_JUMPTO              221
#define ID_PLAY_GOTO                    222
#define IDI_DVD                         222
#define IDD_GOTODIALOG                  223
#define IDD_OPENCAPDEVICEDIALOG         224
#define ID_FILE_OPENDEVICE              225
#define IDD_PPAGETWEAKS                 226
#define ID_PRESETS_43                   227
#define ID_PRESETS_SCALETO169           228
#define IDI_AUDIOCD                     228
#define ID_PRESETS_WIDE                 229
#define ID_PRESETS_UWIDE                230
#define ID_PLAY_FILTERS                 234
#define ID__FILTERS                     235
#define ID_VIEW_SUBRESYNC               236
#define ID_Menu                         237
#define IDB_BITMAP1                     238
#define ID_FILE_SAVESUBTITLES           239
#define ID_PLAY_STEP                    241
#define ID_VIEW_PLAYLIST                242
#define IDD_PLAYERCAPTUREDIALOG         243
#define IDD_CAPTUREDIALOG               243
#define ID_VIEW_CAPTURE                 244
#define ID_HELP_DONATE                  246
#define ID_PANSCAN_MOVELEFT             247
#define ID_PANSCAN_MOVERIGHT            248
#define ID_PANSCAN_MOVEUP               249
#define ID_PANSCAN_MOVEDOWN             250
#define ID_PANSCAN_MOVEUPLEFT           251
#define ID_PANSCAN_MOVEUPRIGHT          252
#define ID_PANSCAN_MOVEDOWNLEFT         253
#define ID_PANSCAN_MOVEDOWNRIGHT        254
#define ID_PANSCAN_CENTER               255
#define ID_HELP_ENTERREGISTRATIONNUMBER 256
#define ID_PLAY_SUBTITLES               259
#define ID_PLAY_AUDIO                   260
#define IDD_PPAGEAUDIOSWITCHER          264
#define ID_VIEW_CAPTIONMENU             267
#define IDR_POPUPMAIN                   270
#define ID_VIEW_VF_HALF                 271
#define ID_VIEW_VF_NORMAL               272
#define ID_VIEW_VF_DOUBLE               273
#define ID_VIEW_VF_STRETCH              274
#define ID_VIEW_VF_FROMINSIDE           275
#define ID_VIEW_VF_FROMOUTSIDE          276
#define ID_NAVIGATE_SUBTITLELANGUAGE    279
#define IDD_PPAGEFILTERS                280
#define IDD_FILEPROPDETAILS             282
#define IDD_FILEPROPCLIP                283
#define ID_FILE_PROPERTIES              285
#define IDB_BITMAP2                     287
#define IDB_LOGO                        288
#define ID_NAVIGATE_JUMPTO289           289
#define IDD_PPAGEREALMEDIA              290
#define IDD_PPAGERMQT                   290
#define ID_FAVORITES_ORGANIZE           291
#define ID_FAVORITES_ADD                292
#define IDD_FAVADD                      293
#define IDD_FAVORGANIZE                 294
#define ID_FILE_OPENCD                  295
#define ID_FAVORITES                    296
#define ID_HELP_SHOWCOMMANDLINESWITCHES 297
#define IDD_PNSPRESETDIALOG             298
#define IDD_PPAGEACCELTBL               299
#define ID_VIEW_TOGGLEALL               300
#define ID_VIEW_PRESETS                 301
#define ID_VIEW_PRESETS_HIDEALL         302
#define ID_PRESETS_MINIMAL303           303
#define ID_PRESETS_NORMAL               304
#define ID_VIEW_HIDEALL                 305
#define ID_VIEW_PRESETS306              306
#define ID_VIEW_PRESETS_NONE            307
#define ID_VIEW_PRESETS_MINIMAL         308
#define ID_VIEW_PRESETS_COMPACT         309
#define ID_VIEW_PRESETS_NORMAL          310
#define IDD_DIALOG1                     311
#define IDD_MEDIATYPEDIALOG             312
#define IDD_MEDIATYPESDIALOG            312
#define ID_FILE_SAVEAS                  313
#define ID_FILE_OPENCD314               314
#define IDD_SAVEDIALOG                  315
#define IDR_AVI1                        316
#define ID_Menu318                      318
#define ID_VIDEOFRAME_KEEPASPECTRATIO   319
#define ID_VIEW_VF_KEEPASPECTRATIO      319
#define ID_Menu320                      320
#define IDI_ICON1                       321
#define IDI_UNKNOWN                     321
#define IDD_SAVETEXTFILEDIALOGTEMPL     322
#define IDD_SAVETEXTFILEDIALOGTEMPL_400 324
#define IDD_ADDREGFILTER                325
#define IDD_DIALOG2                     327
#define IDD_SELECTMEDIATYPE             327
#define IDD_PPAGESUBSTYLE               328
#define IDD_PPAGEMOUSE                  329
#define IDD_PPAGESOURCE                 330
#define IDS_R_SETTINGS                  500
#define IDS_RS_CONTROLSTATE             501
#define IDS_RS_VOLUME                   502
#define IDS_RS_MUTE                     503
#define IDS_RS_BALANCE                  504
#define IDS_RS_LOOP                     505
#define IDS_RS_LOOPNUM                  506
#define IDS_RS_REWIND                   507
#define IDS_RS_ZOOM                     508
#define IDS_RS_HWACCEL                  509
#define IDS_RS_MULTIINST                510
#define IDS_RS_ALWAYSONTOP              511
#define IDS_RS_AUTOZOOM                 512
#define IDS_RS_FULLSCREENCTRLS          513
#define IDS_RS_FULLSCREENCTRLSTIMEOUT   514
#define IDS_RS_VMRRENDERLESS            515
#define IDS_RS_RENDERERTYPE             515
#define IDS_RS_VIDEORENDERERTYPE        515
#define IDS_RS_VMRFLIP                  516
#define IDS_RS_DVDPATH                  517
#define IDS_RS_USEDVDPATH               518
#define IDS_RS_MENULANG                 519
#define IDS_RS_AUDIOLANG                520
#define IDS_RS_SUBTITLESLANG            521
#define IDS_RS_SPLOGFONT                522
#define IDS_RS_SPOUTLINE                523
#define IDS_RS_SPSHADOW                 524
#define IDS_RS_SPSFGCOLOR               525
#define IDS_RS_SPOVERRIDEPLACEMENT      526
#define IDS_RS_SPHORPOS                 527
#define IDS_RS_SPVERPOS                 528
#define IDS_RS_SPCSIZE                  529
#define IDS_RS_SPC16BPP                 530
#define IDS_RS_SPCMAXRES                531
#define IDS_RS_SPCCOMPRESS              532
#define IDS_RS_INTREALMEDIA             533
#define IDS_RS_FAVORWAVEOUT             534
#define IDS_RS_DISABLEXPTOOLBARS        535
#define IDS_RS_USEDEDYNAMIC             536
#define IDS_RS_DBLCLICKFULLSCREEN       537
#define IDS_RS_EXITFULLSCREENATTHEEND   538
#define IDS_RS_AUTOSPEAKERCONF          539
#define IDS_RS_REMEMBERWINDOWPOS        540
#define IDS_RS_LASTWINDOWRECT           541
#define IDS_RS_AUDIORENDERERTYPE        542
#define IDS_RS_SPEAKERTOCHANNELMAPPING  543
#define IDS_RS_CUSTOMCHANNELMAPPING     544
#define IDS_RS_DOWNSAMPLETO441          545
#define IDS_RS_ENABLEAUDIOSWITCHER      546
#define IDS_RS_HIDECAPTIONMENU          547
#define IDS_R_VIDEOFILTERS              548
#define IDS_R_FILTERS                   548
#define IDS_R_AUDIOFILTERS              549
#define IDS_RS_DEFAULTVIDEOFRAME        550
#define IDS_RS_REMEMBERWINDOWSIZE       551
#define IDS_RS_REALMEDIARENDERLESS      552
#define IDS_RS_QUICKTIMERENDERER        553
#define IDS_RS_REALMEDIAFPS             554
#define IDS_RS_AUDIOTIMESHIFT           555
#define IDS_RS_ENABLEAUDIOTIMESHIFT     556
#define IDS_R_FAVFILES                  557
#define IDS_R_FAVDVDS                   558
#define IDS_R_FAVDEVICES                559
#define IDS_R_LOGOFILE                  560
#define IDS_RS_LOGOFILE                 560
#define IDS_RS_ENABLEWORKERTHREADFOROPENING 561
#define IDS_RS_PNSPRESETS               562
#define IDS_RS_AUTOLOADAUDIO            563
#define IDS_RS_AUTOLOADSUBTITLES        564
#define IDS_RS_SEARCHKEYFRAMES          565
#define IDS_RS_ACCELTBL                 566
#define IDS_RS_SETFULLSCREENRES         567
#define IDS_RS_FULLSCREENRES            568
#define IDS_RS_WINLIRCADDR              569
#define IDS_R_COMMANDS                  570
#define IDS_RS_WINLIRC                  571
#define IDS_RS_TRAYICON                 572
#define IDS_RS_KEEPASPECTRATIO          573
#define IDS_RS_UICEADDR                 574
#define IDS_RS_UICE                     575
#define IDS_RS_JUMPDISTS                576
#define IDS_RS_JUMPDISTM                577
#define IDS_RS_JUMPDISTL                578
#define IDS_RS_REPORTFAILEDPINS         579
#define IDS_RS_SRCFILTERS               580
#define IDS_RS_KEEPHISTORY              581
#define IDC_BROWSEBUTTON                1016
#define IDC_BROWSEBUTTON2               1017
#define IDC_COMBO1                      1018
#define IDC_COMBO2                      1019
#define IDC_VOLUMESLIDER                1020
#define IDC_SLIDER2                     1020
#define IDC_COMBO9                      1020
#define IDC_SLIDER3                     1021
#define IDC_COMBO12                     1021
#define IDC_RADIO1                      1022
#define IDC_RADIO2                      1023
#define IDC_EDIT1                       1024
#define IDC_CHECK1                      1025
#define IDC_EDIT4                       1025
#define IDC_SLIDER4                     1026
#define IDC_EDIT2                       1026
#define IDC_COMBO13                     1026
#define IDC_EDIT3                       1027
#define IDC_CHECK9                      1027
#define IDC_CHECK2                      1028
#define IDC_EDIT5                       1028
#define IDC_CHECK3                      1029
#define IDC_EDIT6                       1029
#define IDC_CHECK4                      1030
#define IDC_EDIT7                       1030
#define IDC_CHECK5                      1031
#define IDC_EDIT8                       1031
#define IDC_SPIN1                       1032
#define IDC_SPIN2                       1033
#define IDC_LANGRADIO1                  1034
#define IDC_SPIN3                       1034
#define IDC_LANGRADIO2                  1035
#define IDC_SPIN4                       1035
#define IDC_LANGRADIO3                  1036
#define IDC_SPIN5                       1036
#define IDC_BUTTON1                     1037
#define IDC_LIST1                       1038
#define IDC_SPIN6                       1038
#define IDC_BUTTON5                     1038
#define IDC_LOCRADIO1                   1039
#define IDC_SPIN7                       1039
#define IDC_BUTTON11                    1039
#define IDC_LOCRADIO2                   1040
#define IDC_EDIT9                       1040
#define IDC_BUTTON12                    1040
#define IDC_DVDPATH                     1041
#define IDC_SPIN8                       1041
#define IDC_EDIT12                      1041
#define IDC_BUTTON13                    1041
#define IDC_EDIT10                      1042
#define IDC_BUTTON14                    1042
#define IDC_SPIN9                       1043
#define IDC_RADIO3                      1044
#define IDC_RADIO4                      1045
#define IDC_RADIO5                      1046
#define IDC_RADIO6                      1047
#define IDC_FORMATDESC                  1048
#define IDC_SLIDER5                     1048
#define IDC_RADIO12                     1048
#define IDC_SLIDER6                     1049
#define IDC_RADIO13                     1049
#define IDC_EDIT11                      1050
#define IDC_STATIC_DUB                  1051
#define IDC_SPIN10                      1051
#define IDC_MSG2                        1052
#define IDC_MSG3                        1053
#define IDC_SUBRESYNCLIST               1054
#define IDC_PLAYLIST                    1055
#define IDC_RADIO7                      1056
#define IDC_RADIO8                      1057
#define IDC_RADIO9                      1058
#define IDC_RADIO10                     1059
#define IDC_RADIO11                     1060
#define IDC_COLORPRI                    1063
#define IDC_COLORSEC                    1064
#define IDC_COLOROUTL                   1065
#define IDC_COLORSHAD                   1066
#define IDC_BUTTON3                     1067
#define IDC_BUTTON7                     1068
#define IDC_COMBO3                      1069
#define IDC_COMBO4                      1070
#define IDC_COMBO5                      1071
#define IDC_COMBO6                      1072
#define IDC_COMBO7                      1073
#define IDC_COMBO8                      1074
#define IDC_COMBO10                     1075
#define IDC_COMBO11                     1076
#define IDC_BUTTON2                     1077
#define IDC_CHECK6                      1078
#define IDC_BUTTON6                     1078
#define IDC_CHECK7                      1079
#define IDC_BUTTON9                     1079
#define IDC_LIST2                       1080
#define IDC_BUTTON10                    1080
#define IDC_BUTTON4                     1081
#define IDC_BUTTON15                    1081
#define IDC_LIST3                       1082
#define IDC_BUTTON8                     1083
#define IDC_DEFAULTICON                 1085
#define IDC_TAB1                        1088
#define IDC_CHECK8                      1089
#define IDC_PLACEHOLDER                 1090
#define IDC_CUSTOM1                     1091
#define IDC_SHOCKWAVEFLASH              1092
#define IDC_STATIC1                     1093
#define IDC_STATIC2                     1094
#define IDC_STATIC3                     1095
#define IDC_STATIC4                     1096
#define IDC_IPADDRESS1                  1097
#define IDC_STATICLINK                  1099
#define IDC_ANIMATE1                    1100
#define IDC_STATICLINK2                 1100
#define IDC_PROGRESS1                   1101
#define IDC_REPORT                      1102
#define IDC_FROMTO                      1105
#define IDC_TYPE                        1106
#define IDC_TREE2                       1108
#define IDD_COMPROPERTYPAGE             10002
#define ID_DUMMYSEPARATOR               32768
#define ID_VOLUME_MUTE_ON               32769
#define ID_VOLUME_MUTE_DISABLED         32770
#define ID_BUTTONSEP                    32771
#define ID_PLAY_FRAMESTEP               32773
#define ID_PLAY_FRAMESTEPCANCEL         32774
#define ID_PLAY_SEEKKEYBACKWARD         32777
#define ID_PLAY_SEEKKEYFORWARD          32778
#define ID_FILE_POST_OPENMEDIA          32779
#define ID_FILE_POST_CLOSEMEDIA         32780
#define ID_NAVIGATE_MENU_LEFT           32781
#define ID_NAVIGATE_MENU_RIGHT          32782
#define ID_NAVIGATE_MENU_UP             32783
#define ID_NAVIGATE_MENU_DOWN           32784
#define ID_NAVIGATE_MENU_ACTIVATE       32785
#define ID_NAVIGATE_MENU_BACK           32786
#define ID_NAVIGATE_MENU_LEAVE          32787
#define ID_VIEW_FULLSCREEN_SECONDARY    32788
#define ID_PLAY_SEEKBACKWARDSMALL       32789
#define ID_PLAY_SEEKFORWARDSMALL        32790
#define ID_PLAY_SEEKBACKWARDMED         32791
#define ID_PLAY_SEEKFORWARDMED          32792
#define ID_PLAY_SEEKBACKWARDLARGE       32793
#define ID_PLAY_SEEKFORWARDLARGE        32794
#define ID_BOSS                         32795
#define ID_MENU_PLAYER_SHORT            32796
#define ID_MENU_PLAYER_LONG             32797
#define ID_MENU_FILTERS                 32798
#define ID_STREAM_AUDIO_NEXT            32799
#define ID_STREAM_AUDIO_PREV            32800
#define ID_STREAM_SUB_NEXT              32801
#define ID_STREAM_SUB_PREV              32802
#define ID_OGM_AUDIO_NEXT               32803
#define ID_OGM_AUDIO_PREV               32804
#define ID_OGM_SUB_NEXT                 32805
#define ID_OGM_SUB_PREV                 32806
#define ID_DVD_ANGLE_NEXT               32807
#define ID_DVD_ANGLE_PREV               32808
#define ID_DVD_AUDIO_NEXT               32809
#define ID_DVD_AUDIO_PREV               32810
#define ID_DVD_SUB_NEXT                 32811
#define ID_DVD_SUB_PREV                 32812
#define ID_FILE_RELOADCURRENT           32813
#define ID_FILE_OPENCD32814             32814
#define ID_FILTERS_SUBITEM_START        33000
#define ID_FILTERS_SUBITEM_END          33099
#define ID_FILTERSTREAMS_SUBITEM_START  33100
#define ID_FILTERSTREAMS_SUBITEM_END    33199
#define ID_AUDIO_SUBITEM_START          33200
#define ID_AUDIO_SUBITEM_END            33299
#define ID_SUBTITLES_SUBITEM_START      33300
#define ID_SUBTITLES_SUBITEM_END        33399
#define ID_NAVIGATE_CHAP_SUBITEM_START  33400
#define ID_NAVIGATE_CHAP_SUBITEM_END    33499
#define ID_NAVIGATE_AUDIO_SUBITEM_START 33500
#define ID_NAVIGATE_AUDIO_SUBITEM_END   33599
#define ID_NAVIGATE_SUBP_SUBITEM_START  33600
#define ID_NAVIGATE_SUBP_SUBITEM_END    33699
#define ID_NAVIGATE_ANGLE_SUBITEM_START 33700
#define ID_NAVIGATE_ANGLE_SUBITEM_END   33799
#define ID_FAVORITES_FILE_START         33800
#define ID_FAVORITES_FILE_END           34799
#define ID_FAVORITES_DVD_START          34800
#define ID_FAVORITES_DVD_END            34899
#define ID_FAVORITES_DEVICE_START       34900
#define ID_FAVORITES_DEVICE_END         34999
#define ID_FILE_OPEN_CD_START           35000
#define ID_FILE_OPEN_CD_END             35099
#define ID_PANNSCAN_PRESETS_START       35100
#define ID_PANNSCAN_PRESETS_END         35199

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           10003
#endif
#endif
